horusec-analytic/cmd/app/main.go
horusec-analytic/docs/docs.go
horusec-analytic/docs/swagger.json
horusec-analytic/docs/swagger.yaml
horusec-analytic/internal/handlers/dashboard/dashboard.go
horusec-analytic/internal/router/router.go

Swagger is not visible in global auth middleware, change to specific routes

Fixing swagger in horusec-analytics

---

development-kit/pkg/engines/examples/leaks-php/wp-config.php
development-kit/pkg/engines/leaks/analysis/analysis_test.go
development-kit/pkg/enums/engine/advisories/leaks/leaks.go
development-kit/pkg/enums/engine/advisories/leaks/leaks_test.go
development-kit/pkg/enums/engine/advisories/leaks/regular/regular.go

Add a new leak regular rule to find wp-config expressions.
There is a new example file and a new unit test, run: ` go test -v ./development-kit/pkg/engines/leaks/analysis -timeout=2m -parallel=1 -failfast -short`

Add new leak regular rule: WPConfig file exposed

---

development-kit/pkg/engines/leaks/analysis/analysis_test.go
development-kit/pkg/enums/engine/advisories/leaks/regular/regular.go
development-kit/pkg/enums/engine/advisories/leaks/regular/regular_test.go

Adding unit tests in all rules of horusec-leaks
Upgrade rules of:
* Wordpress configuration file disclosure
* Potential Hard-coded credential

Adding vulnerabilities tests for horusec-leaks rules

---

horusec-messages/internal/controllers/email/templates/email_confirmation.go
horusec-messages/internal/controllers/email/templates/organization_invite.go
horusec-messages/internal/controllers/email/templates/reset_password.go

🛠  Fixing broken URL of horusec logo in template e-mail

[Hotfix] - Horusec Logo in template emails.

---

development-kit/pkg/entities/analyser/python/output.go
horusec-cli/README.md
horusec-cli/internal/services/formatters/csharp/scs/formatter.go
horusec-cli/internal/services/formatters/javascript/npmaudit/formatter.go
horusec-cli/internal/services/formatters/javascript/yarnaudit/formatter.go
horusec-cli/internal/services/formatters/python/bandit/formatter.go
horusec-cli/internal/services/formatters/python/safety/formatter.go
horusec-cli/internal/services/formatters/service.go
horusec-manager/package-lock.json

Fixing filepaths

---

horusec-manager/.semver.yaml
horusec-manager/src/helpers/localStorage/currentLanguage.ts
horusec-manager/src/helpers/localStorage/currentUser.ts
horusec-manager/src/helpers/localStorage/horusecConfig.ts

Changed the functions in the manager that use JSON.parse so that you can use it in a safer way and not cause an error in the application if something unexpected occurs.

Added safe JSON parse in manager

---

.github/workflows/cli-pipeline.yml
Makefile
horusec-cli/deployments/scripts/update-image.sh

Added arguments to build the Horusec binary without dynamic link with libc. Alpine Linux doesn't have by default support to Glibc, `go build` link dynamically with it if you don't add explicit arguments to build without any dynamic link library.
Build and copy Horusec binary to an Alpine container.
```
$ export GOPATH=$HOME/go
$ export PATH=$PATH:$GOPATH/bin
$ make build-install-cli
$ docker run -it -v $GOPATH:/go alpine:latest sh
$ cd /go/bin
$ ./horusec version
```
Add arguments for the building binary without any dynamic link library (run to the Alpine Linux)

Added support to Alpine Linux

---

internal/services/engines/csharp/rules.go
internal/services/engines/dart/rules.go
internal/services/engines/java/rules.go
internal/services/engines/jvm/rules.go
internal/services/engines/kotlin/rules.go
internal/services/engines/kubernetes/rules.go
internal/services/engines/nginx/rules.go
internal/services/engines/nodejs/rules.go
internal/services/formatters/csharp/horuseccsharp/formatter.go
internal/services/formatters/dart/horusecdart/formatter.go
internal/services/formatters/default_engine_formatter.go
internal/services/formatters/java/horusecjava/formatter.go
internal/services/formatters/javascript/horusecnodejs/formatter.go
internal/services/formatters/kotlin/horuseckotlin/formatter.go
internal/services/formatters/leaks/horusecleaks/formatter.go
internal/services/formatters/nginx/horusecnginx/formatter.go
internal/services/formatters/yaml/horuseckubernetes/formatter.go

Create a default formatter to be used on implementations of Horusec
engines. Previously each engine implement your own version of Formatter
with very common steps. This commit introduce a new formatter that can be
reused between all the engines just passing the rules and languages of
each engine.

Create default formatter

---

internal/services/engines/csharp/rules.go
internal/services/engines/dart/rules.go
internal/services/engines/java/rules.go
internal/services/engines/jvm/rules.go
internal/services/engines/kotlin/rules.go
internal/services/engines/kubernetes/rules.go
internal/services/engines/leaks/rules.go
internal/services/engines/nginx/rules.go
internal/services/engines/nodejs/rules.go
internal/services/formatters/csharp/horuseccsharp/formatter.go
internal/services/formatters/dart/horusecdart/formatter.go
internal/services/formatters/default_engine_formatter.go
internal/services/formatters/java/horusecjava/formatter.go
internal/services/formatters/javascript/horusecnodejs/formatter.go
internal/services/formatters/kotlin/horuseckotlin/formatter.go
internal/services/formatters/leaks/horusecleaks/formatter.go
internal/services/formatters/nginx/horusecnginx/formatter.go
internal/services/formatters/yaml/horuseckubernetes/formatter.go

Create a default formatter to be used on implementations of Horusec
engines. Previously each engine implement your own version of Formatter
with very common steps. This commit introduce a new formatter that can be
reused between all the engines just passing the rules and languages of
each engine.

create default formatter to all horusec engines (#465)

---

internal/services/engines/csharp/rules.go
internal/services/engines/csharp/rules_test.go
internal/services/engines/dart/rules.go
internal/services/engines/dart/rules_test.go
internal/services/engines/java/rules.go
internal/services/engines/java/rules_test.go
internal/services/engines/jvm/rules.go
internal/services/engines/jvm/rules_test.go
internal/services/engines/kotlin/rules.go
internal/services/engines/kotlin/rules_test.go
internal/services/engines/kubernetes/rules.go
internal/services/engines/kubernetes/rules_test.go
internal/services/engines/leaks/rules.go
internal/services/engines/leaks/rules_test.go
internal/services/engines/nginx/rules.go
internal/services/engines/nginx/rules_test.go
internal/services/engines/nodejs/rules.go
internal/services/engines/nodejs/rules_test.go
internal/services/engines/rules.go

Create a default rule manager implementation to be used between all
engines to load rules and text units. Previously each rule implements
its own version of RuleManager to load the rules and text units, with
common steps between them, just changing the GetRules implementation to
return the rules of specific language, with this new default
implementation we can just pass this rules to constructor and use the
same logic to all engines. 
I'm also update the tests of Kotlin and Java to count the rules of jvm, and make them more easily to read.

create default rule manager

---

go.mod
go.sum
internal/services/docker/client/docker_config.go
internal/services/docker/client/docker_config_mock.go
internal/services/docker/docker_api.go
internal/services/docker/docker_api_test.go

`golang.org/x/net/context` is a alias to `context` package in std lib, so this PR replace the import to std lib directly and remove unnecessary dependency. 

replace golang.org/x/net/context to std context

---

internal/controllers/analyzer/analyzer.go

Previously, to warn the user that the analysis is still running, we used
time.Sleep to print how much time is left for the timeout, however, if the
analysis has already been completed, we still need to wait for the end of
time.Sleep to finish the analysis. This change removes time.Sleep and uses
time.Tick to print the message, so, if the analysis is finished before the
next retry, we do not lock the analysis with time.Sleep.

avoid time.Sleep to log analysis timeout status

---

internal/controllers/analyzer/analyzer.go

Initiated `projectSubPath` into new variable separate from the loop, avoiding variable sharing between threads. Fix for ZupIT/horusec#497
Running horusec CLI with multiple workdirs for a language will process all defined directories
Fixed workdir config only working on 1 directory

Fixing error where variable pointer is shared between processes

---

.github/workflows/build.yaml
internal/enums/toignore/to_ignore.go
internal/enums/toignore/to_ignore_test.go

Signed-off-by: nathanmartinszup <nathan.martins@zup.com.br>

Removing some unnecessary paths ignored by horusec

---

.github/workflows/e2e.yml
e2e/scan_languages/scan_languages_test.go

This commit refactor the end-to-end tests to assert for equal
vulnerabilities instead for assert that vulnerabilities is greater
than 0. This commit also refactor the tests to use table tests for more
readability and avoid duplicated code.

tests: refactor end-to-end tests

---

examples/javascript/example2/app.js
internal/services/engines/nodejs/regular/regular.go
internal/services/engines/nodejs/rules.go
internal/services/engines/rules_test.go

- Redirect unsafe
- No render content from request
- No write content from request on HTML
- Expose stack trace
- Insecure download of executable file
- Add readFileSync in regex of NoReadFileUsingDataFromRequest() rule

Javascript rules improve

---

README.md
e2e/scan_languages/scan_languages_test.go
internal/services/git/git.go

Fixing issue #581
Horusec failing when start compilation on windows because is necessary usage double cottle for accept commands

Fix commit authors on windows 

---

cmd/app/generate/generate.go
cmd/app/generate/generate_test.go
cmd/app/main.go
cmd/app/start/start.go
config/config.go
config/config_test.go

Previously we are reading and evaluating the config values on every
command of CLI, even if we don't needed. For example, when we ran the
version command we create the log files. So this commit change to read
and merge config values and create the log file only when needed.

cli: fix unnecessary log file creation

---

internal/services/engines/java/and/and.go
internal/services/engines/java/rules.go
internal/services/engines/rules_test.go

In the transition through Eclipse Foundation, the package has changed to `jakarta` instead of `javax`
I need help to create unit tests for each new method. Could you help me with that?
Ref: https://eclipse-foundation.blog/2020/12/08/jakarta-ee-9-delivers-the-big-bang/

Adds support to Jakarta package instead of javax

---

.github/workflows/build.yaml
.github/workflows/coverage.yml
.github/workflows/dco.yaml
.github/workflows/e2e.yml
.github/workflows/license.yaml
.github/workflows/lint.yml
.github/workflows/security.yml
.github/workflows/test.yml

This commit change the workflows to run only on pull requests instead on
push. With this change pull requests from contributors outside the ZupIT
organization will run.

ci: fix workflows not running on pull requests

---

internal/controllers/analyzer/analyzer.go
internal/controllers/analyzer/analyzer_test.go
internal/entities/workdir/workdir.go
internal/entities/workdir/workdir_test.go
internal/services/docker/docker_api.go
internal/services/formatters/generic/trivy/formatter.go
internal/usecases/cli/cli.go

Previously some tools that we execute on Docker were running
synchronously. This commit fix this issue to execute all tools and
analysis in parallel. A benchmark was made using the Go examples
directory.
Before change:
goos: linux
goarch: amd64
pkg: github.com/ZupIT/horusec/internal/controllers/analyzer
cpu: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
BenchmarkAnalyzerAnalyze
BenchmarkAnalyzerAnalyze-4                 1        33251799589 ns/op        4095008 B/op      20445 allocs/op
ok      github.com/ZupIT/horusec/internal/controllers/analyzer  33.305s
After change:
goos: linux
goarch: amd64
pkg: github.com/ZupIT/horusec/internal/controllers/analyzer
cpu: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
BenchmarkAnalyzerAnalyze
BenchmarkAnalyzerAnalyze-4                 1        17626114733 ns/op …

analyzer: improve performance to execute tools on Docker

---

.github/workflows/lint.yml

This commit change the workflow of lint to install Go on a specific
version. Without Go installation we are getting a random version of
Go on CI causing failing on pipelines.

ci: install Go on lint workflow

---

cmd/app/generate/generate_test.go
cmd/app/start/start_test.go
internal/controllers/analyzer/analyzer_test.go
internal/services/custom_rules/service.go
internal/services/docker/client/docker_config_test.go
internal/services/docker/docker_api.go
internal/services/docker/docker_api_test.go
internal/services/horusec_api/horus_api.go
internal/services/horusec_api/horus_api_test.go

Since Go 1.16 the io/ioutil package was deprecated, so this commit
change the usage of io/ioutil functions to io and os packages.
https://golang.org/doc/go1.16#ioutil

all: remove usage of io/ioutil package

---

internal/services/formatters/service.go

Add the rule id to the vulnerability details. This id will only be
shown when a vulnerability is found by horusec-engine.

cli: add rule id on details of Vulnerability

---

cmd/app/start/start.go

cli: fix parse of custom-rule-path flag

---

renovate.json

Change commit message template of renovate bot to:
deps: update \<old\> to \<new\>

renovate: change commit message template

---

cmd/app/start/start.go
cmd/app/start/start_test.go
config/config.go
config/config_test.go
internal/controllers/language_detect/language_detect.go

Previously we are parsing the config values in follow order:
command line flags -> config file -> env variables.
This commit fix the order to parse in follow order:
config file -> env variables -> command line flags.
Since the func passed to PreRun field on cobra command is executed after
the command line parsing, a change was made on CreateStartCommand method
to call the config methods to load the values from config file and
environment variables before creating the cobra command, so when the
PreRun is execute the only thing that is needed to do is normalize the
values and setup the log configuration.

config: fix flags not overriding config file and env variables

---

internal/services/formatters/generic/trivy/config.go

Trivy docker container was shared for both checks and both commands were writing to same file amending 2 jsons incorrectly, this commit change it to different files to solve this problem

trivy: fix trivy parsing error

---

internal/controllers/language_detect/language_detect.go
internal/controllers/language_detect/language_detect_test.go
internal/enums/toignore/to_ignore.go
internal/usecases/cli/cli_test.go

this commits updates language detect tests and some file matching checks now using filepath.Join(), removing ReplacePathSeparator usages on this package as discussed in #719 and fix to_ignore paths to run as it should

language_detect: improve tests, file matching checks and to_ignore paths

---

cmd/app/start/start.go
cmd/app/start/start_test.go
config/config.go
internal/controllers/language_detect/language_detect.go
internal/controllers/printresults/print_results.go
internal/controllers/requirements/docker/docker.go
internal/controllers/requirements/git/git.go
internal/entities/docker/analysis_data_test.go
internal/helpers/messages/debug.go
internal/helpers/messages/error.go
internal/helpers/messages/info.go
internal/helpers/messages/panic.go
internal/helpers/messages/trace.go
internal/helpers/messages/warn.go
internal/services/formatters/csharp/dotnet_cli/formatter.go
internal/services/formatters/javascript/npmaudit/formatter.go
internal/services/formatters/javascript/npmaudit/formatter_test.go
internal/usecases/cli/cli.go
internal/usecases/cli/cli_test.go

Some error messages were with the warning type naming, so I changed them so they all had the correct naming.
Another change was that the error message file had two types of messages:
* Return messages in functions like fmt.Errorf or errros.New
* Error log messages in functions such as logger.LogError or logger.LogErrorWithLevel

Fix position and responsability of logs into horusec

---

internal/services/engines/nodejs/rules.go
internal/services/engines/nodejs/rules_test.go
internal/services/engines/nodejs/samples_test.go

Create tests for rules HS-JAVASCRIPT-9, HS-JAVASCRIPT-10,
HS-JAVASCRIPT-11, HS-JAVASCRIPT-12, HS-JAVASCRIPT-13, HS-JAVASCRIPT-14,
HS-JAVASCRIPT-15, HS-JAVASCRIPT-16, HS-JAVASCRIPT-17, HS-JAVASCRIPT-18
Note that the regex from rule HS-JAVASCRIPT-9 was changed to
optionally match `$` on where field since this is not valid on
sequealize https://sequelize.org/master/manual/model-querying-basics.html#applying-where-clauses
Note too that this commit fix the regex of rule HS-JAVASCRIPT-16 that
was not matching indentation.
Updates #630

engine/nodejs: create tests for rules

---

internal/controllers/analyzer/analyzer.go
internal/controllers/analyzer/analyzer_test.go

Previously when we set the log level for debug the output is hard to
read since the we are printing the debug messages and the scan loading.
This commit change the newScanLoading constructor to set the writer of
loading to io.Discard when the log level is debug or trace.

analyzer: disable scan loading when debug level log is set

---

internal/helpers/messages/debug.go
internal/services/docker/docker_api.go
internal/services/docker/docker_api_test.go

Previously when we call `checkIfImageNotExists` function we check for
errors and if image does not exists on the same statement and only log
if some errors occurs, which turn the code a bit confuse to read.
This commit change to check for errors and if image does not exists on
different statements and also add a debug logging to inform that image
does not exists on cache and we will try to pull from registry.
This commit also add some tests to assert that we are pulling the image
only if its not exists on cache.

docker: improvement logs on pulling image

---

internal/services/docker/client/docker_config.go
internal/services/docker/client/docker_config_test.go

Previously when an user use a different DOCKER_HOST we was not able to
connect because we was not reading the environment variables.
This commit change the docker client initialization to read
configuration from environment variables if they exists.
Fixes #525

feat:docker: use env variables to configure docker client

---

internal/controllers/analyzer/analyzer.go
internal/services/formatters/leaks/deployments/Dockerfile
internal/services/formatters/leaks/gitleaks/config.go

- Removed unnecessary apk add from leaks dockerfile that was causing an error during the image build.
- Changed gitleaks config to use its own tool's flag for json export.
- Fixed a bug that broke analysis loading due to a warning stating that the git history is active.

gitleaks-chore: fixing gitleaks formatter error and improving config

---

internal/controllers/analyzer/analyzer.go
internal/services/horusec_api/horus_api.go
internal/services/horusec_api/horus_api_mock.go
internal/services/horusec_api/horus_api_test.go

Changed SendAnalysis and GetAnalysis to return errors, so we can treat them and completely refactor on tests

horus_api:chore - improving horus_api.go functions and tests

---

internal/controllers/printresults/print_results.go
internal/controllers/printresults/print_results_test.go

This commit add new tests to cover Sonarqube output type and add asserts
to check if what was printed is correctly.
The tests was changed to use table testings approach to make more easily
to add a new testcase.
The PrintResults implementation was improved too. Basically a new
io.Writer field was added to customize where we will write outputs. The
default constructor will always write to Stdout, but on tests we use a
custom BufferString to write.
This commit also make some improvements on code organization and private
method names.
Updates #718

printresults:chore - add tests to cover output and Sonarqube output type

---

config/config.go
config/config_test.go
internal/entities/toolsconfig/tools_config.go
internal/entities/toolsconfig/tools_config_test.go
internal/services/formatters/c/flawfinder/formatter_test.go
internal/services/formatters/csharp/dotnet_cli/formatter_test.go
internal/services/formatters/csharp/scs/formatter_test.go
internal/services/formatters/elixir/mixaudit/formatter_test.go
internal/services/formatters/elixir/sobelow/formatter_test.go
internal/services/formatters/generic/dependency_check/formatter_test.go
internal/services/formatters/generic/semgrep/formatter_test.go
internal/services/formatters/generic/trivy/formatter_test.go
internal/services/formatters/go/gosec/formatter_test.go
internal/services/formatters/go/nancy/formatter_test.go
internal/services/formatters/hcl/checkov/formatter_test.go
internal/services/formatters/hcl/tfsec/formatter_test.go
internal/services/formatters/javascript/npmaudit/formatter_test.go
internal/services/formatters/javascript/yarnaudit/formatter_test.go
internal/services/formatters/leaks/gitleaks/formatter_test.go
internal/services/formatters/php/phpcs/formatter_test.go
internal/services/formatters/python/bandit/formatter_test.go
internal/services/formatters/python/safety/formatter_test.go
internal/services/formatters/ruby/brakeman/formatter_test.go
internal/services/formatters/ruby/bundler/formatter_test.go
internal/services/formatters/service_test.go
internal/services/formatters/shell/shellcheck/formatter_test.go

Previously the toolsconfig package does not have any unit tests and the
public functions and types was a bit confused, since two types was
exported to represents the same "thing".
This commit implements the tests to cover scenarios of toolsconfig
parsing.
This commit also rename ToolsConfigStruct to toolsConfig and also made
private, since this struct is only used as schema to parse the values
and only the Map type is used by other packages. The Map and Config
struct was also renamed to don't be repetitive on names.
The function ParseInterfaceToMapToolsConfig was also renamed to
MustParseToolsConfig to follow the Go standards of functions that can
cause errors that will be not returned. The signature was also changed
to avoid bugs when accepting an empty interface{}, since the viper will …

toolsconfig:chore: create tests and rename public objects

---

e2e/commands/start/start_test.go

End to end test for the `--request-timeout` flag.

e2e:chore - test for the request timeout flag

---

config/config.go
config/config_test.go
internal/controllers/analyzer/analyzer.go
internal/entities/custom_images/custom_images.go
internal/entities/custom_images/custom_images_test.go
internal/helpers/messages/error.go
internal/services/formatters/service.go

Previously the implementation of CustomImages map was a bit redundant.
Basically a map[string]string was created using the string
representation of each languages.language as key, and when were we going
to access this map we always receive a languages.Language and need to get
the string representation of this language, which make an unnecessary type
casting.
This commit change the type of CustomImages to store a
languages.Language as key and avoid these type casting.
The function `NewCustomImages` was renamed to `Default` to make more
clear and a new function `MustParseCustomImages` was created to parse
the input taken from Viper.
This commit also add some new tests to assert the default values and
test the parsing.
Updates #718
Signed-off-by: Matheus Alcantara …

customimages:chore - avoid type casting and add tests

---

README.md

readme: add -L flag on install command for windows

readme:hotfix  - add -L flag on install command for windows

---

internal/services/engines/nodejs/rules.go

Pull request to improve the assertiveness of `HS-JAVASCRIPT-4` and `HS-JAVASCRIPT-5` rules to target cases as reported in #768.

engine:chore - improve rules HS-JAVASCRIPT-4 and HS-JAVASCRIPT-5

---

internal/entities/custom_rules/custom_rule.go
internal/entities/custom_rules/custom_rule_test.go

customrules:chore - add new tests to cover all supported languages

---

internal/utils/vuln_hash/vuln_hash_test.go

Previously the testcases of vulnhash package does not assert the
generated hash using all the fields used to generate the hash.
This commit change the testcases to assert the generated hash with all
fields filled.
The testcase also was change to assert the valid and invalid generated
hash
Updates #718

vulnhash:chore - improvement tests asserts

---

internal/helpers/messages/error.go
internal/services/formatters/service.go
internal/services/formatters/service_test.go

Previously when running the Horusec on Windows we was getting a
different vulnerability hash for each analysis, this problem was
happening because we weren't removing the .horusec folder from
the file path before generating the hash, and since the .horusec folder
contains a uuid, on every analysis we was getting a new uuid and
consequently a new vulnerability hash.
The commit fix this issue using a better approach to remove the .horusec
folder from filepath, using the relative path from file using the
.horusec folder as base path.
This commit also change the testcase to catch this bug.
This bug was founded on #777

formatters:hotfix - fix random vulnerability hash on Windows

---

internal/services/engines/nodejs/rules.go
internal/services/engines/nodejs/rules_test.go
internal/services/engines/nodejs/samples_test.go
internal/utils/testutil/examples.go

In issue #765 we have a scenario that our rule was not able to detect the vulnerability.
In order for it to be more assertive, I suggest a more assertive change in the rule matcher, however this implies confidentiality, that I needed to change it to LOW.

engine:chore - improve the HS-JAVASCRIPT-02 rule

---

e2e/commands/start/start_test.go
internal/entities/custom_images/custom_images_test.go
internal/entities/toolsconfig/tools_config_test.go

Tests e2e for risk accepted and false positive flags.

e2e:chore - tests for risk accepted and false positive flags

---

cmd/app/start/start.go
internal/controllers/analyzer/analyzer.go
internal/entities/custom_rules/custom_rule.go
internal/services/engines/javascript/rule_manager.go
internal/services/engines/javascript/rules.go
internal/services/engines/javascript/rules_test.go
internal/services/engines/javascript/samples_test.go
internal/services/engines/rules_test.go
internal/services/formatters/default_engine_formatter_test.go
internal/services/formatters/javascript/horusecjavascript/formatter.go

Rename the nodejs engine service to javascript

engine:chore - rename the nodejs engine service to javascript

---

internal/utils/copy/copy.go
internal/utils/copy/copy_test.go

Previously if some symlink exists on project path during the copy we was
creating a directory instead evaluating the sysmlink.
Evaluating the symlink makes us need to deal with several scenarios,
such as, how should we copy a file to the .horuse folder when it is not
in the project path? Another scenario would be how do we handle symlinks
from files that don't exist on the user's machine?
With that in mind, this commit changes the behavior of the `Copy` function
to ignore symlinks by default and only copy directories and files. Since
previously we were no longer analyzing sysmlinks, this change will not be
noticed by the user.
This commit also change the assertiveness of tests to check if all files
and directories was copied correctly.
Updates #718
Signed-off-by: Matheus Alcantara …

utils/copy:chore - skip symlink files and improve tests assertiveness

---

e2e/commands/start/start_test.go

E2e test for the --monitor-retry-count flag
run `make test-e2e` and expected all tests passed.
N/A

e2e:chore - test for the monitor retry count flag

---

cmd/app/start/start.go
cmd/app/start/start_test.go
internal/usecases/cli/cli.go
internal/usecases/cli/cli_test.go

This commit remove an unnecessary empty `UseCases` struct and change
their methods to functions and change the references to this struct to
call the public function directly.
Some private functions from this package was renamed to have consistency
between all of them.
Removing this struct we also remove an unnecessary heap allocation since
the `NewCLIUseCases()` function return a pointer to this struct.
The heap allocation was noticed using the
github.com/jordanlewis/gcassert using the `gcassert:noescape` directive
on cmd/app/start/start.go:68:
```
gcassert ./cmd/app/start/
cmd/app/start/start.go:75:useCases: cli.NewCLIUseCases(): &cli.UseCases{} escapes to heap:
```
**- Description for …

usecases/cli:chore - remove unnecessary UseCases struct

---

internal/controllers/printresults/print_results.go
internal/controllers/printresults/print_results_test.go

printresults: fix wrong filepath when using --container-bind-project-path

---

e2e/commands/start/start_test.go

E2e test for the `--information-severity`
run `make test-e2e` and expected all tests passed.
N/A

e2e:chore - test for the information severity flag

---

internal/services/formatters/c/flawfinder/formatter.go
internal/services/formatters/c/flawfinder/formatter_test.go
internal/services/formatters/c/flawfinder/result.go
internal/services/formatters/c/flawfinder/result_test.go

Improves the test cases of errors to verify that errors were actually
added to the analysis. Some asserts was also added on success tests to
verify that the parsing is correctly and all fields is filled.
This commit also move schema definition of flawfinder results from
flawfinder/entities to flawfinder package and make them private.
Finally some code organization was made and redundant code was removed.
Updates #718

flawfinder:chore - improve tests asserts and code cleaning

---

internal/services/engines/java/rules.go
internal/services/engines/swift/rule_manager.go
internal/services/engines/swift/rules.go
internal/services/engines/swift/rules_test.go
internal/services/engines/swift/samples_test.go

- Add rule to HS-SWIFT-24
- Was removed HS-SWIFT-1 because: This rule is not affective, if need you can see this thread https://stackoverflow.com/questions/1718929/should-i-use-sqlite3-finalize-after-i-performed-a-query-with-sqlite3-exec

engine:chore - improvement tests for rules of the swift

---

internal/enums/images/images.go

This commit upgrade the tags for almost all languages that is supported
by Horusec.
Python was not upgraded because the safety and bandit was not released
with official support for Python 3.10.
Generic and HCL was not upgraded too because we need to upgrade the
installation script of tools that is installed on Dockerfile (tfsec,
semgrep and dependency check) which will be done separately.

images:chore - upgrade Docker tags

---

internal/controllers/analyzer/analyzer.go
internal/entities/docker/analysis_data.go
internal/services/docker/docker_api.go
internal/services/formatters/javascript/npmaudit/formatter.go
internal/services/formatters/javascript/yarnaudit/formatter.go
internal/services/formatters/ruby/bundler/formatter.go

Previously on npm audit, yarn audit and bundler audit we use fmt.Sprintf
to join file path which cause bugs on Windows.
This commit replace these usages to use filepath.Join instead.
This commit also replace Sprintf usages on Docker images paths to use
path.Join which is appropriate to deal with slash-separated paths. Note
that the `path` package is (and should) only used to handle paths that
are separated by forward slashes which is the case of Docker images.
Read more from path package: https://pkg.go.dev/path

all:chore - replace Sprintf to filepath|path.Join to join paths

---

internal/controllers/printresults/print_results.go
internal/controllers/printresults/print_results_test.go

On #760 we made an improvement on `getDefaultTotalVulnBySeverity` which
reuse the map returned from `getDefaultCountBySeverity` as a value for
all keys on the default map of vulnerability severities, but since a map
in Go is a pointer we was using the same map to all keys and when we
were going to count vulnerabilities by severity, we would update the
same pointer for all the keys in that map, which caused inconsistent
and duplicated values in the final result.
This commit revert this change and call pr.getDefaultCountBySeverity for
all keys on this map.

printresults:fix - duplicated vulnerability severities on result

---

internal/services/formatters/csharp/dotnet_cli/formatter.go
internal/services/formatters/go/nancy/formatter.go
internal/services/formatters/go/nancy/formatter_test.go
internal/utils/file/file.go
internal/utils/file/file_test.go

Previously when we execute Nany, we was searching the vulnerability only
on go.mod files, but Nancy analyse go.sum files too, so when some
vulnerability returned by Nany that is only  declared on go.sum the
vulnerability result show a File without file name (only the project
path) and the Code and Line empty.
This commit change the function `GetDependencyCodeFilepathAndLine` to
receive a list of extensions that can match on the given projectPath, so
the Nancy formatter was changed to pass .mod and .sum extensions. Since
the function signature was changed to be variadic the references was
changed too to follow the new parameter orders.
The success test case was also changed to cover this scenario.
**- How to …

nancy:fix - empty file name, code and line on vulnerability result

---

internal/controllers/language_detect/language_detect_test.go

language_detect:bugfix - improve tests to use config.New()

---

cmd/app/start/start.go

cli:fix - typo on description of enable-shellcheck flag

---

internal/services/formatters/service.go
internal/services/formatters/service_test.go
internal/services/git/git.go
internal/services/git/git_test.go

- Changing function that removes default src/ horusec folder from filepath to prevent it being reported as `/hcl/example1/main.tf`, which will be looked up from root and break git blame function. Now it will return the correted path 
like this `hcl/example1/main.tf`
- Added flag `--no-patch` into git blame function to avoid diff info. Without it, in some cases will return extra information and break the json parse. Following the example of the output that results in error.
```
{
"author": "Otávio Santana",
"email":"otaviopolianasantana@gmail.com",
"message": "Updates sample to Java Vulnerabilities (#4)",
"date": "2021-12-02 08:22:25 -0300",
"commitHash": "3aea61743d526c833f0a3ddf289807dafa505370"
}
diff --git …
```

services/git:bugfix - error git diff breaking parse and invalid filepath

---

Makefile
cmd/app/start/start.go
internal/controllers/analyzer/analyzer.go
internal/helpers/messages/panic.go

Previously we control all execution of tools using a `monitor` package,
but this package contained a lot of data races that was fixed on #477
and the monitor retry count flag was no longer necessary, since this was
used to control the timeout counter.
This commit mark monitor-retry-count flag as hidden and deprecated, so
new users will not see this flag and users that is currently using this
flag on pipelines will see a warning saying to use just --analysis-timeout
flag.

cli:chore - deprecate monitor-retry-count flag

---

cmd/app/start/start.go
internal/helpers/messages/error.go

On cobra if `runE` return an error the usage is showed automatically and
the error message is printed, so this commit remove an unnecessary log
error and a call to `cmd.Help()` function which print the usage of help
command twice.

cli:fix - duplicate show usage on validation errors

---

deployments/Dockerfile

Previously we was download the dependencies using `go get`, but since we
are using go modules, a better approach should be use `go mod download`
to download and cache all dependencies.
This commit also add a new build flags on binary to remove debug
information which will make de final binary smaller.

deployments/Dockerfile:chore - improve approach to build cli

---

.github/workflows/alpha.yml
deployments/Dockerfile-gorelease-amd64
deployments/Dockerfile-gorelease-arm64
go.mod
go.sum
goreleaser.yml

Replaced workflow action used to publish the release, also had to change binary names to match the actual name in release, since the new action does not support renaming during publish. The binary names changes let to another change, i had to change the goreleaser Dockerfiles to match correct binary according to architecture.
Depends on a new devkit tag with the https://github.com/ZupIT/horusec-devkit/pull/140 fixes.

alpha:bugfix - fixing errors with alpha workflow publish release

---

internal/controllers/language_detect/language_detect.go
internal/controllers/language_detect/language_detect_test.go

Previously when checking which files should be ignored by analysis on
Windows the directories patterns was not working properly, this is
because we was expecting that these paths would be always Unix like
paths so when a user set a path `**/tests/**` we can not ignore the
tests directory on Windows since the path would be `**\\tests\\**`.
This commit fix this issue converting all paths and all patterns to Unix
like paths before checking if should be ignored. Now `**/tests/**` would
match both `foo/bar/tests` and `foo\\bar\\tests`.
If the user set the pattern to use Windows slashes like `**\\tests\\**`,
this will work correctly only on Windows, so it is recommend that users
should always use the Unix slashes when configuring patterns that should
be ignored by analysis.
Signed-off-by: …

language_detect:fix ignore files correctly on Windows

---

internal/services/engines/java/rule_manager.go
internal/services/engines/java/rules.go
internal/services/engines/java/rules_test.go
internal/services/engines/java/sample_test.go
internal/services/engines/rules_test.go

engine/java:feature - adding log4j remote code injection rule

---

internal/services/formatters/service.go
internal/services/formatters/service_test.go
internal/utils/file/file.go
internal/utils/file/file_test.go

Previously when we were running on Windows we was setting a Windows path
as a work dir inside a Docker container. For example, we start the
analysis, and we try to find a path that contains go.mod files, we found
the path C:\user\some\path and we was using this path (with Windows
slashes) as a work dir on Docker, so when the command try to access this
path (cd some\path) we was getting errors.
This commit fix this issue converting any path to Unix path before
replacing the {{WORK_DIR}} of command.
Some tests of formatter was changed to expected that any path used on
{{WORK_DIR}} should be a Unix like path.
This commit also make some improvements on `utils/file` private
functions, resolving a TODO by refactoring the function to use a better
approach to get the relative directory of a file …

formatters:fix - invalid work dir path on Windows

---

deployments/scripts/install.sh

> :warning: SHOULD BE MERGE ONLY WHEN THE NEXT RELEASE WITH THE BINARIES NAME CHANGES WAS RELEASED.
This pull request contains changes to the new standard binaries names, that were changed in the pr #702.
Now binaries are sepated by archicteture, and this made needed a change to the install script, on the next release the binaries names will change and this pull request contains a validation to the old and the new standard.

scripts:feature - updating install script to the new binary standard

---

deployments/scripts/install.sh

Updating install script validation to cover the beta and rc new tags. The `isOldURL Version` function checks for versions before `2.6.4`, for this the function remove special characters leaving only numbers and verify if the version is greater than the informed version. The validation was not removing beta and rc data from the version. Removed duplicated `echo` informing the version and fixed error in latest version `echo` printing the beta version.

scripts:bugfix - fixing error in url validation with latest rc and beta

---

magefile.go

Fixes the following error with the Built field:
```
Version:          v2.6.5
Git commit:       ee72d9f844d2448a491f2cd564321c1b5cccd2fa
Built:            $(date "+%a %b %d %H:%M:%S %Y")
Distribution:     normal
```

mage:bugfix - fixing error that cli date was being print equal the date command

---

internal/controllers/analyzer/analyzer.go
internal/controllers/analyzer/analyzer_test.go

Previously when use use the flag --information-severity the information
vulnerabilities was not been printing by PrintResults, this is because we
was getting a conflict between --information-severity and
--ignore-severity flags, the default values of --ignore-severity is INFO,
so when we use the flag --information-severity we was still not printing
because the INFO vulnerabilities was been ignored by --ignored-severity
flag.
This commit fix this issue by forcing the print of INFO vulnerabilities
when --information-severity is enabled.
Fixes #785

analyzer:fix - not printing information severity when enabled

---

internal/services/formatters/ruby/deployments/Dockerfile

Bundler on version 0.9.0 had a bug that make the execution crash, this
commit upgrade to version 0.9.0.1 that contains a fix for this issue.
Read more: https://github.com/rubysec/bundler-audit/issues/319
This commit also change the Dockerfile do install Git, since on 2.7.x
images is not installed by default, and is a requirement to execute
Bundler.
https://github.com/rubysec/bundler-audit#requirements

formatters/bundler:fix upgrade to fix crash on execution

---

internal/services/engines/java/rules.go
internal/services/engines/java/sample_test.go

Updated rule HS-JAVA-150 to match log4j when it's lower than 2.16.0. Also made a improvement in regex to avoid false positives with futures version like 3.0.0.

engine/java:chore - updating JS-JAVA-150 to match log4j lower than 2.16.0

---

internal/services/engines/java/rules.go
internal/services/engines/java/sample_test.go

engine/java:chore - updating log4j rule to match versions before 2.17

---

internal/services/formatters/generic/trivy/formatter.go
internal/utils/file/file.go

Signed-off-by: Danang Heriyadi <danang.heriyadi19@gmail.com>
Tried to solve https://github.com/ZupIT/horusec/issues/881 bug by adding some code to find where the correct line. I am not sure it's effective or not. But it's work.  In my code, I define the start line from 0, is that correct?
```bash
$ git clone https://github.com/sqreen/go-dvwa.git
$ cd go-dvwa
$ horusec generate
$ horusec start -p $(pwd)
```
Check Horusec report on the go.sum file it will show as below:
```bash
==================================================================================
Language: Generic
Severity: UNKNOWN
Line: 73
Column: 0
SecurityTool: Trivy
Confidence: MEDIUM
File: /home/danang/Project/Horusec/go-dvwa/go.sum
Code: github.com/gin-gonic/gin
Details: Installed …
```

formatters/trivy:fix - find correct line of dependency

---

internal/helpers/messages/debug.go
internal/services/formatters/ruby/brakeman/formatter.go
internal/services/formatters/ruby/brakeman/formatter_test.go
internal/services/formatters/service.go
internal/utils/file/file.go

If there was no `Gemfile` file in the current directory, Brakeman would
generate an error stating that the project to be analyzed was not a Ruby
on Rails project.
This commit fix this issue by looking for a directory path that contains
a `Gemfile` filename and them using this path as a work dir to execute
Brakeman.

brakeman:fix - search for Gemfile's before start analysis 

---

internal/controllers/language_detect/language_detect.go

Previously during the walk path, for each path visited, before append
the new path on the list of paths we were always checking for duplicate
values, which make a redundant operation, since this check can be only
be done once. Before return the languages we was checking for duplicate
languages (again) and also converting the languages from string to
`languages.Language` and checking if their supported, which add another
redundant loop on `languages.Values()`, since we can only ignore unknown
languages during the parsing.
This commit remove this redundant code by checking only once for
duplicate languages, and ignoring `languages.Unknown` during
parsing/appending to all languages list. …

language_detect:chore - remove redundant code

---

internal/services/formatters/generic/dependency_check/analysis.go
internal/services/formatters/generic/dependency_check/dependency.go
internal/services/formatters/generic/dependency_check/dependency_test.go
internal/services/formatters/generic/dependency_check/formatter.go
internal/services/formatters/generic/dependency_check/formatter_test.go
internal/services/formatters/generic/dependency_check/vulnerability.go
internal/services/formatters/generic/dependency_check/vulnerability_test.go

This commit add some new asserts on successful parsing dependency check
results, to verify that all fields of Vulnerability was filled.
removed and the dependency check schema output was moved to
dependencycheck package.
Updates #718

dependency_check:chore - improve tests and code cleaning

---

internal/entities/docker/analysis_data.go
internal/entities/docker/analysis_data_test.go
internal/services/docker/docker_api_test.go
internal/services/formatters/c/flawfinder/formatter.go
internal/services/formatters/csharp/dotnet_cli/formatter.go
internal/services/formatters/csharp/scs/formatter.go
internal/services/formatters/elixir/mixaudit/formatter.go
internal/services/formatters/elixir/sobelow/formatter.go
internal/services/formatters/generic/dependency_check/formatter.go
internal/services/formatters/generic/semgrep/formatter.go
internal/services/formatters/generic/trivy/formatter.go
internal/services/formatters/go/gosec/formatter.go
internal/services/formatters/go/nancy/formatter.go
internal/services/formatters/hcl/checkov/formatter.go
internal/services/formatters/hcl/tfsec/formatter.go
internal/services/formatters/javascript/npmaudit/formatter.go
internal/services/formatters/javascript/yarnaudit/formatter.go
internal/services/formatters/leaks/gitleaks/formatter.go
internal/services/formatters/php/phpcs/formatter.go
internal/services/formatters/python/bandit/formatter.go
internal/services/formatters/python/safety/formatter.go
internal/services/formatters/ruby/brakeman/formatter.go
internal/services/formatters/ruby/bundler/formatter.go
internal/services/formatters/shell/shellcheck/formatter.go

This commit rename `SetData` to `SetImage` to avoid confusion since
`SetData` is too generic and it doesn't make it clear which data is
being modified.

docker:chore - rename SetData method of AnalysisData

---

internal/services/formatters/hcl/checkov/check.go
internal/services/formatters/hcl/checkov/check_test.go
internal/services/formatters/hcl/checkov/config.go
internal/services/formatters/hcl/checkov/formatter.go
internal/services/formatters/hcl/checkov/formatter_test.go
internal/services/formatters/hcl/checkov/result.go
internal/services/formatters/hcl/checkov/summary.go
internal/services/formatters/hcl/checkov/vulnerability.go

This commit add some new asserts on successful parsing Checkov results
to verify that all fields of Vulnerability was filled.
removed and the Checkov schema output was moved to checkov package.
Updates #718

checkov:chore - improve tests and code cleaning

---

internal/services/formatters/hcl/tfsec/formatter.go
internal/services/formatters/hcl/tfsec/formatter_test.go
internal/services/formatters/hcl/tfsec/location.go
internal/services/formatters/hcl/tfsec/result.go
internal/services/formatters/hcl/tfsec/result_test.go
internal/services/formatters/hcl/tfsec/vulnerabilities.go

This commit add some new asserts on successful parsing tfsec results
to verify that all fields of Vulnerability was filled.
removed and the tfsec schema output was moved to tfsec package.
Updates #718

tfsec:chore - improve tests and code cleaning

---

internal/services/engines/java/rules.go
internal/services/engines/java/sample_test.go

log4j:chore - update log4j min version to 2.17.1

---

.github/workflows/security.yml
internal/enums/images/images.go
internal/helpers/messages/error.go
internal/services/formatters/go/deployments/Dockerfile
internal/services/formatters/go/nancy/formatter.go
internal/services/formatters/go/nancy/formatter_test.go

The nancy tool requires access to the Github API's, but when accessed several times without an identification
it is blocked until the user identifies himself using an authentication token that can be generated via Github,
so I created a validation for this scenario and the user can add this environment variable before starting an analysis.
Run many times GoLang project and see follow error:
```bash
Invalid character 'E' looking for beginning of value
```
Error not handled by Horusec in Nancy tool [#905](https://github.com/ZupIT/horusec/issues/905)

nancy:chore - Error not handled by Horusec in Nancy tool

---

internal/services/formatters/javascript/npmaudit/formatter_test.go
internal/services/formatters/javascript/yarnaudit/finding.go
internal/services/formatters/javascript/yarnaudit/formatter.go
internal/services/formatters/javascript/yarnaudit/formatter_test.go
internal/services/formatters/javascript/yarnaudit/issue.go
internal/services/formatters/javascript/yarnaudit/issue_test.go
internal/services/formatters/javascript/yarnaudit/metadata.go
internal/services/formatters/javascript/yarnaudit/output.go
internal/services/formatters/javascript/yarnaudit/vulnerabilities.go

This commit add some new asserts on successful parsing yarn results
to verify that all fields of Vulnerability was filled.
Note that the test cases from `TestParseOutputNpm`(yes, it was
misspelled) was moved to `TestYarnAuditParseOutput` to centralize
all tests as it is done in the other tests of the other formatters.
removed and the yarn schema output was moved to yarnaudit package.
Updates #718

yarnaudit:chore - improve tests and code cleaning

---

cmd/app/start/start.go
internal/controllers/analyzer/analyzer.go
internal/controllers/analyzer/analyzer_test.go
internal/controllers/analyzer/runner.go

Previously the Analyzer struct holds the entire pipeline of an analysis,
which add a lot of complexity, since this pipeline has a lot of steps:
Detect languages, orchestrate tools by languages, send analysis to Horusec
manager and them print the results on stdout.
This commit split the Analyzer struct into a new struct `runner`.
This new struct will be responsible only to orchestrate all tools to
their respective languages. The coded implemented on runner is basically
a copy and paste from Analyzer implementation, so the behavior remains
the same.
Some documentation was also added to try do make more clear what are the
steps that Analyzer do, and what a runner means.
**- Description for …

analyzer:chore - split analyzer implementation into runner

---

internal/services/formatters/default_engine_formatter.go
internal/services/formatters/default_engine_formatter_test.go
internal/services/formatters/interface.go
internal/services/formatters/service.go
internal/services/formatters/service_test.go
internal/utils/testutil/formatter_mock.go

Since the `GetCommitAuthor` was just being used internally by
IService implementation there's no reason to keep this method, and as
pointed by @iancardosozup, on `GetProjectPathWithWorkDir` docs, their
usage can be simple changed by a `filepath.Join` call, so this method was
removed too.

formatters:chore - remove unused methods from IService

---

internal/services/formatters/go/nancy/formatter.go

Previously for each analysis a warning log was being printed informing
an error of Github API rate limit from Nancy. This commit change this
behaviour to just log in debug level that Nancy was ignored because the
GITHUB_TOKEN env is not set.
Fixes #920

nancy:chore - remove logs when running without GITHUB_TOKEN env

---

internal/services/formatters/ruby/bundler/formatter.go

Previously when a project path does not have a Gemfile.lock file, the
Bundler return an error `Could not find "Gemfile.lock"` that was being
interpreted as a vulnerability. This was happening because the commit
https://github.com/rubysec/bundler-audit/commit/021f85f change the error
message from a generic error like "Errno::ENOENT" and "No such file or
directory" to a more detailed error `Could not find "Gemfile.lock"`.
Fixes #919

bundler:fix - correctly parse output error

---

internal/services/formatters/ruby/bundler/criticality.go
internal/services/formatters/ruby/bundler/formatter.go
internal/services/formatters/ruby/bundler/formatter_test.go
internal/services/formatters/ruby/bundler/output.go

This commit add some new asserts on successful parsing bundler results
to verify that all fields of Vulnerability was filled.
Some code organization was also made, and the entities and enum packages
was removed and the bundler schema output was moved to bundler package.
This commit also fix a bug when parsing invalid output from Bundler.
The `strings.Split(output, "Name:")` on `parseOutput` return a list with
one element when the split fails, so when Bundler return an output that
is not expected we still try to parse this invalid output which results
invalid vulnerabilities. To fix this a validation was added before the
split to check if output contains the `Name:` field.
Updates #718 …

bundler:chore - improve tests and code cleaning

---

internal/services/formatters/go/gosec/formatter_test.go
internal/services/formatters/go/nancy/formatter_test.go
internal/services/formatters/service.go
internal/services/formatters/service_test.go

Previously if some tool generate an error and this was first error that
occurred in the analysis the error message does not show the tool that
generate this error, only from the second error the tool was informed.

formatters:fix - not show which tool generate the error

---

internal/services/formatters/generic/trivy/formatter.go

Since the pull request https://github.com/ZupIT/horusec/pull/882 some
changes were made in the line and code of the trivy formatter,
and this data influences directly the hash generation.
This pr will avoid this hash change by using the same data as
before, but for the users the data will be showed with the fixes
made in the pull request 882, leading to no braking changes
and keeping the fixes.

trivy:bugfix - adding func to avoid hash changes in trivy formatter

---

internal/services/engines/swift/rules.go
internal/services/engines/swift/rules_test.go
internal/services/engines/swift/samples_test.go

engine/swift:bugfix - improving HS-SWIFT-24 rule to avoid false positives

---

internal/services/formatters/hcl/tfsec/result.go

Tfsec func resposable por getting the severeties of the vulnerabilities
was in a wrong format, leading to vulnerablities without severity and
this vulnerabilities were being ignored. This pull request fixes this
error by updating the func to match the correct tfsec severities
https://github.com/aquasecurity/tfsec/blob/master/pkg/severity/severity.go.

formatters/tfsec:bugfix - vulnerabilities were being ignored due missing severity

---

internal/controllers/requirements/docker/docker.go

Signed-off-by: Luis Guilherme de A <luisguilhermepdea@gmail.com>
I changed the way the version of docker is retrieved, from a shell command execution to Docker API.
This pull-request solves the issue    #757 
With the docker running, run the horusec and it will validate the Docker version, from the Docker API.
The log error message of an error with the docker validation had changed. Now few steps of preprocessing are necessary to retrieve the version.

[docker]:[feature] - Validate Docker version from the Docker API

---

cmd/app/start/start.go
internal/controllers/printresults/print_results.go
internal/enums/outputtype/output_type.go
internal/helpers/messages/info.go
internal/services/sarif/sarif.go
internal/services/sarif/sarif_test.go
internal/services/sarif/schema.go
internal/usecases/cli/cli.go

Signed-off-by: Anthony Turner <225599+anthturner@users.noreply.github.com>
Added SARIF-compatible output structures as an output option in the same vein as SonarQube
Use `-o sarif` as an option with Horusec to output a SARIF report
Adds SARIF output support
---
Want to note that this is not necessarily complete; there are several things which just don't exist in Horusec right now. For example, I notice not all of the engine modules have RuleIDs populated, and there is other metadata (such as URL) which need to have a lookup table or some other place to pull them from. This might mean authoring a `.csv` file to track the metadata or maybe embedding it into code somehow is better.
Hopefully this at least helps get the conversation started.
* See also #937

SARIF Output Support

---

Makefile

The latest release of gci formatter come with a bug[1] that generate an
error to format files that use dot imports. This commit fix the previous
version to avoid errors on make format until the bug is fixed.
[1] https://github.com/daixiang0/gci/issues/44

makefile:chore - bump gci tool

---

internal/services/formatters/generic/semgrep/config.go
internal/services/formatters/generic/semgrep/formatter.go

In this commit I change semgrep tool to not collect information
of the your analysis. And I found an error in Log when semgrep
fails was showing the tool name wrong.

fix:semgrep - Disable collect metrics and fix log message

---

internal/services/engines/jvm/rules.go
internal/services/engines/jvm/rules_test.go
internal/services/engines/jvm/samples_test.go

Previously the rules of encode/decode Base64 was reporting any string
that had the value encode/decode which was generating a lot of false
positive. This commit improve the regex of these rules to catch only
the method call that match encode or decode on name.
The type of rule HS-JVM-24 was changed from AndMatch to OrMatch to
follow the same behaviour of HS-JVM-28.
Fixes #816

engines/jvm:fix - false positives on base64 encode/decode

---

internal/helpers/messages/error.go
internal/services/formatters/csharp/dotnet_cli/formatter.go
internal/services/formatters/csharp/scs/formatter.go
internal/services/formatters/elixir/sobelow/formatter.go
internal/services/formatters/generic/trivy/formatter.go
internal/services/formatters/generic/trivy/formatter_test.go
internal/services/formatters/go/nancy/formatter.go
internal/services/formatters/interface.go
internal/services/formatters/javascript/npmaudit/formatter.go
internal/services/formatters/javascript/yarnaudit/formatter.go
internal/services/formatters/php/phpcs/formatter.go
internal/services/formatters/php/phpcs/formatter_test.go
internal/services/formatters/python/safety/formatter.go
internal/services/formatters/ruby/brakeman/formatter.go
internal/services/formatters/ruby/bundler/formatter.go
internal/services/formatters/ruby/bundler/formatter_test.go
internal/services/formatters/service.go
internal/services/formatters/service_test.go
internal/utils/file/file.go
internal/utils/file/file_test.go
internal/utils/testutil/formatter_mock.go

Fix a bug in internal/utils/file.go where line value wasn't being restored to 0 when loop restarted, adding error return to GetDependencyCodeFilepathAndLine and GetDependencyInfo and some logging messages when this error is found. Removed unused function ReplacePathSeparator. Also changed some LogError to LogErrorWithLevel and setting errors to analysisError to be print on analysis end

commitAuthors:bugfix - fix when pass invalid line to SetCommitAuthors

---

deployments/Dockerfile
deployments/Dockerfile-gorelease-amd64
deployments/Dockerfile-gorelease-arm64

With the apk update && apk upgrade commands for some reason goreleaser
was't hable to build the images. This pr updates the dockerfiles to use
a diferent base image of the docker that doesn't contains the expat
vulnerabilities.

dockerfiles:bugfix - updating docker base image

---

internal/services/engines/jvm/rules_test.go
internal/services/formatters/csharp/deployments/Dockerfile
internal/services/formatters/csharp/scs/config.go

Originally this pr was open by renovate to update the dotnet to the
version 7.0, but the security code scan sill don't support it. So
I had downgraded it to 6.0. Also added a new flag --ignore-msbuild-errors
to avoid some uncessary errors during the analysis.

deps:chore - update dependency mcr.microsoft.com/dotnet/sdk to v6

---

config/config.go
internal/controllers/analyzer/analyzer.go
internal/services/engines/jvm/rules_test.go
internal/services/formatters/leaks/gitleaks/formatter.go
internal/services/formatters/python/bandit/formatter.go
internal/services/formatters/python/safety/formatter.go
internal/services/formatters/service.go
internal/services/horusec_api/horus_api_test.go
internal/services/sarif/sarif.go
internal/utils/testutil/docker_mock.go

Look in this commit I commented the test in `horus_api_test.go`,
because in local machine this works fine, but in github actions don't
and I don't know what us can do.

lint:chore - Fix lint, format and Horusec API tests

---

go.mod
go.sum
internal/controllers/analyzer/analyzer.go
internal/controllers/analyzer/analyzer_test.go
internal/controllers/printresults/print_results.go
internal/controllers/printresults/print_results_test.go
internal/helpers/messages/warn.go
internal/services/formatters/csharp/dotnet_cli/formatter.go
internal/services/formatters/csharp/dotnet_cli/formatter_test.go
internal/services/formatters/generic/trivy/formatter.go
internal/services/formatters/service_test.go
internal/utils/vuln_hash/vuln_hash.go
internal/utils/vuln_hash/vuln_hash_test.go

Currently cli generates very volatile hashes, any commit, description
changes will change the hash, wich is a problem to the vulnerabilities
management. This pull request changes the way that we generate the hash
to use only the code, line and file, this way we expect that the hash
will be more estable. In this pull request we also added a tratative to
handle with the future depreciation of the old hashes that we still
consider valid. So all users should update the oldated hashes, the cli
is going to show a warning with the necessary hashes to update and the
new ones.

hash:feature - new hash format and handle the future depreciations

---

internal/controllers/analyzer/analyzer.go
internal/controllers/printresults/print_results.go

Both errors and warnings are handled using the same field, this causes a
lot of confusion and a very complex code.
This pull request removes warnings from the errors field, and adds them
to the specific field for warnings. In the future with the refactoring
of formaters this code can be removed, but for now it is a necessary
workaround.

analyzer:bugfix - separate warnings from errors

---

.github/CODEOWNERS
.github/workflows/release-alpha.yml
.github/workflows/release-beta.yml
.github/workflows/release-final.yml
.github/workflows/release-rc.yml
goreleaser.yml

In this PR I'll update Release Beta, RC and Final to set automatic
body in release notes. I changed file release-new.yml to
release-final.yml and I changed file alpha.yml to release-alpha.yml

workflow:feat - Automating the release notes

---

internal/services/sarif/sarif.go

Sarif validator reports an error if the version contains the v prefix.
This pull request remove this prefix for the sarif output.

sarif:bugfix - removing version prefix

---

internal/enums/images/images.go
internal/services/formatters/csharp/scs/formatter.go

scs:bugfix - att outdated chsharp sdk on horusec-engine-csharp

---

internal/controllers/analyzer/analyzer.go
internal/helpers/messages/warn.go
internal/services/formatters/ruby/brakeman/formatter.go
internal/services/formatters/ruby/bundler/formatter.go

Previously if the project had ruby between programming languages but is
not a ruby on rails project or does not have a Gemfile.lock an error
would be reported for each scenario.
This pull request changes these error messages introduced in commits
cd839ef and 9245d7d to be considered just warnings, as there is no
need to point them out as errors, since it is only intended to
inform the user.

formatters/ruby:chore - removing unnecessary error messages

---

goreleaser.yml

Before every release was released as a draft, in this way it was
possible to define which releases should be published as a pre release
and which not. After pull request 578e883, all releases are published
directly without the possibility to define betas and rcs as pre
releases.
This pull request changes the goreleaser configuration file to
automatically define which ones should be published as pre releases.
For this the pre release:auto attribute was added, for more information
follow the documentation link
https://goreleaser.com/customization/release/?h=release#release.

goreleaser:bugfix - adding release auto

---

internal/utils/file/file.go

utils/file:fix - missing {HORUSEC_CLI} prefix and typo on log debug

---

internal/services/engines/leaks/rules.go
internal/services/engines/leaks/rules_test.go
internal/services/engines/leaks/samples.go

In this commit I changed to add Safe and Unsafe code
in all rules of the leaks.  Reference from issue #630 and #1020.

leaks:chore - Adding improvements on leaks rules

---

internal/services/engines/java/rules.go

**- Increased the severity of XXE rules in Java to High**
XXE attacks can lead to high or critical damage according to their contexts. Since the goal of SAST is to Reduce security Risk by decreasing Impact and Likelihood, we should consider the worst-case scenario when dealing with this kind of Injection. Because of that, its wise to consider XXE findings as High Severity without given context (which SAST is unable to discover)
Signed-off-by: gustavomarinhozup <gustavo.marinho@zup.com.br>

Increased all XXE severities in Java Rules to High

---

internal/controllers/language_detect/language_detect_test.go
internal/controllers/requirements/docker/docker.go
internal/utils/file/file_test.go

Changed how we check the docker version to accept single digits.
More about the issue here: [https://github.com/ZupIT/horusec/issues/1154](https://github.com/ZupIT/horusec/issues/1154)
Also, this issue can be connected: [https://github.com/ZupIT/horusec/issues/1155](https://github.com/ZupIT/horusec/issues/1155)
I also changed some tests that run on "make test" - as two tests failed locally.
**More details:**
When we validate the docker version, we read the version and subversion from specific characters of the string that represent the version. As in some cases, subversion has one digit instead of two, subversion's string consists of a number and "." for example, "0.". When we pass such string to strconv.Atoi, we receive an error. This cause the error in version …

start:bugfix wrong interpretation of subversion of docker
