horusec-account/.semver.yaml, horusec-api/.semver.yaml, horusec-cli/internal/services/formatters/java/horusecjava/config.go, horusec-cli/internal/services/formatters/kotlin/horuseckotlin/config.go, horusec-cli/internal/services/formatters/leaks/horusecleaks/config.go, horusec-java/.semver.yaml, horusec-kotlin/.semver.yaml, horusec-leaks/.semver.yaml
=> [skip ci] update versioning file

horusec-manager/package.json, horusec-manager/src/components/Footer/index.tsx
Get and show the version of package.json in the footer component.
=> Show front-end version of package.json

horusec-manager/src/components/PrivateRoute/index.tsx, horusec-manager/src/helpers/localStorage/currentCompany.ts, horusec-manager/src/helpers/localStorage/currentUser.ts, horusec-manager/src/routes/auth.routes.tsx, horusec-manager/src/routes/index.tsx
Adjusting redirect routes when the call is external of manager. 
Ex:  Confirmation Email -> Horusec manager
=> Fixing redirect external routes

horusec-manager/src/components/Select/index.tsx, horusec-manager/src/config/i18n/enUS.json, horusec-manager/src/config/i18n/ptBR.json, horusec-manager/src/config/themes/dark.ts, horusec-manager/src/helpers/hooks/useResponseMessage.ts, horusec-manager/src/helpers/interfaces/Company.ts, horusec-manager/src/pages/Internal/Company/List/Tokens/Add/Sucess/index.tsx, horusec-manager/src/pages/Internal/Company/List/Tokens/Add/Sucess/styled.ts, horusec-manager/src/pages/Internal/Company/List/Tokens/Add/index.tsx, horusec-manager/src/pages/Internal/Company/List/Tokens/Add/styled.ts, horusec-manager/src/pages/Internal/Company/List/Tokens/index.tsx, horusec-manager/src/pages/Internal/Company/List/Tokens/styled.ts, horusec-manager/src/pages/Internal/Company/List/index.tsx, horusec-manager/src/pages/Internal/Company/List/styled.ts, horusec-manager/src/pages/Internal/Home/Dashboard/Filters/index.tsx, horusec-manager/src/pages/Internal/Home/Repositories/Tokens/Add/Sucess/styled.ts, horusec-manager/src/pages/Internal/Home/Users/Invite/index.tsx, horusec-manager/src/services/analytic.ts, horusec-manager/src/services/company.ts
🔑 Handler tokens of organization
Dependes on #33
=> Tokens of organization

.github/workflows/account-pipeline.yml, .github/workflows/analytic-pipeline.yml, .github/workflows/api-pipeline.yml, .github/workflows/cli-pipeline.yml, .github/workflows/development-kit-pipeline.yml, .github/workflows/e2e.yml, .github/workflows/java-pipeline.yml, .github/workflows/kotlin-pipeline.yml, .github/workflows/leaks-pipeline.yml, .github/workflows/manager-pipeline.yml, .github/workflows/messages-pipeline.yml, .github/workflows/security-pipeline.yml, horusec-cli/README.md
Not running github actions on third pull requests
=> Fixing not running github actions

development-kit/pkg/utils/file/file.go, horusec-cli/internal/controllers/language_detect/language_detect.go, horusec-cli/internal/helpers/messages/debug.go, horusec-cli/internal/helpers/messages/error.go, horusec-cli/internal/services/formatters/dotnet/scs/formatter.go, horusec-cli/internal/services/formatters/golang/gosec/formatter.go, horusec-cli/internal/services/formatters/hcl/formatter.go, horusec-cli/internal/services/formatters/java/horusecjava/formatter.go, horusec-cli/internal/services/formatters/java/spotbugs/formatter.go, horusec-cli/internal/services/formatters/javascript/npmaudit/formatter.go, horusec-cli/internal/services/formatters/javascript/yarnaudit/formatter.go, horusec-cli/internal/services/formatters/kotlin/horuseckotlin/formatter.go, horusec-cli/internal/services/formatters/leaks/gitleaks/formatter.go, horusec-cli/internal/services/formatters/leaks/horusecleaks/formatter.go, horusec-cli/internal/services/formatters/python/bandit/formatter.go, horusec-cli/internal/services/formatters/python/safety/formatter.go, horusec-cli/internal/services/formatters/ruby/brakeman/formatter.go, horusec-cli/internal/services/formatters/service.go, horusec-cli/internal/services/formatters/service_mock.go, horusec-cli/internal/services/formatters/service_test.go, horusec-config.json
Fixing error when not found yarn.lock or package-lock.json and fixing not ignore multiple paths
=> Fixing error when not found yarn.lock or package-lock.json and fixing not ignore multiple paths

horusec-manager/src/components/Dialog/index.tsx, horusec-manager/src/components/Select/styled.ts, horusec-manager/src/pages/Internal/Home/Dashboard/styled.ts, horusec-manager/src/pages/Internal/Home/Repositories/Add/index.tsx, horusec-manager/src/pages/Internal/Home/Repositories/Edit/index.tsx, horusec-manager/src/pages/Internal/Home/Repositories/Tokens/Add/index.tsx, horusec-manager/src/pages/Internal/Home/Users/Edit/index.tsx, horusec-manager/src/pages/Internal/Home/Users/Invite/index.tsx
- Fixing background in select component.
- Add scrollbar in dashboard.
- Adjusting colors of buttons in dialog component.
=> Adjusting styles

horusec-manager/src/components/Permissions/index.tsx, horusec-manager/src/components/Select/index.tsx, horusec-manager/src/config/i18n/enUS.json, horusec-manager/src/config/i18n/ptBR.json, horusec-manager/src/pages/External/CreateAccount/Password/index.tsx, horusec-manager/src/pages/Internal/Company/List/Tokens/Add/index.tsx, horusec-manager/src/pages/Internal/Home/Repositories/Add/index.tsx, horusec-manager/src/pages/Internal/Home/Repositories/Invite/index.tsx, horusec-manager/src/pages/Internal/Home/Users/Edit/index.tsx, horusec-manager/src/pages/Internal/Home/Users/Invite/index.tsx, horusec-manager/src/pages/Internal/Home/Users/index.tsx
Adjusting the texts in portugueses in frontend.
=> Adjusting the texts in portugueses

horusec-manager/src/assets/svg/error.svg, horusec-manager/src/assets/svg/success.svg, horusec-manager/src/components/Flash/styled.ts, horusec-manager/src/config/i18n/enUS.json, horusec-manager/src/config/i18n/ptBR.json, horusec-manager/src/contexts/Company.tsx, horusec-manager/src/contexts/FlashMessage.tsx, horusec-manager/src/helpers/enums/flashMessageType.ts, horusec-manager/src/helpers/hooks/useFlashMessage.ts, horusec-manager/src/helpers/hooks/useResponseMessage.ts, horusec-manager/src/pages/Internal/Company/List/Tokens/index.tsx, horusec-manager/src/pages/Internal/Home/Repositories/Add/index.tsx, horusec-manager/src/pages/Internal/Home/Repositories/Edit/index.tsx, horusec-manager/src/pages/Internal/Home/Repositories/Invite/index.tsx, horusec-manager/src/pages/Internal/Home/Repositories/Tokens/index.tsx, horusec-manager/src/pages/Internal/Home/Repositories/index.tsx, horusec-manager/src/pages/Internal/Home/Users/Edit/index.tsx, horusec-manager/src/pages/Internal/Home/Users/Invite/index.tsx, horusec-manager/src/pages/Internal/Home/Users/index.tsx
- Add type for success in Flash Message component.
- Add Success in all handler requests.
=> Success messages

README.md
Added table of contents in readme.md
Added TOC(Table of contents) in Readme.md for issue #56 
It can be found in this Pull Request.
Table of contents made Readme more effective to use and makes it easy to hop in the documentation.
=> Update README.md by adding Table of Contents.

development-kit/pkg/enums/engine/advisories/java/regular/regular.go
=> Fixing regex d34b3ba5-b988-4a0f-9344-467274cd98be

horusec-manager/src/assets/svg/info.svg, horusec-manager/src/components/Select/index.tsx, horusec-manager/src/components/Select/styled.ts, horusec-manager/src/config/i18n/enUS.json, horusec-manager/src/config/i18n/ptBR.json, horusec-manager/src/config/themes/dark.ts, horusec-manager/src/helpers/hooks/useAuth.ts, horusec-manager/src/helpers/hooks/useFlashMessage.ts, horusec-manager/src/helpers/interfaces/FIlterVuln.ts, horusec-manager/src/helpers/interfaces/Pagination.ts, horusec-manager/src/pages/Internal/Home/Vulnerabilities/Details/index.tsx, horusec-manager/src/pages/Internal/Home/Vulnerabilities/index.tsx, horusec-manager/src/pages/Internal/Home/Vulnerabilities/styled.ts, horusec-manager/src/services/repository.ts
=> [Frontend] Improvements false positive

horusec-api/internal/router/router.go
=> List vulnerabilities in management screen to repository members

horusec-manager/package-lock.json, horusec-manager/package.json
Fixing dependenced in horusec-manager
=> Fixing dependences in horusec-manager

development-kit/pkg/engines/leaks/analysis/analysis_test.go
Create test for regular rule HardcodedInURL
=> Add test for HardcodedInURL

horusec-messages/internal/controllers/email/templates/email_confirmation.go, horusec-messages/internal/controllers/email/templates/organization_invite.go, horusec-messages/internal/controllers/email/templates/reset_password.go
Translate the template of emails to english.
=> Template emails english

horusec-lp/src/resources/i18n/locale/en-us.json, horusec-lp/src/resources/i18n/locale/pt-br.json
=> Fixing text ptBR/enUS in LP

development-kit/pkg/entities/account/account.go, development-kit/pkg/entities/account/account_test.go, development-kit/pkg/entities/account/create_account_from_keycloak_response.go, development-kit/pkg/entities/auth/authorization_data.go, development-kit/pkg/services/middlewares/horusec_authz.go, horusec-auth/cmd/app/main.go, horusec-auth/config/app/app.go, horusec-auth/docs/docs.go, horusec-auth/docs/swagger.json, horusec-auth/docs/swagger.yaml, horusec-auth/internal/controller/account/account.go, horusec-auth/internal/controller/account/account_mock.go, horusec-auth/internal/controller/account/account_test.go, horusec-auth/internal/handler/account/account.go, horusec-auth/internal/handler/account/account_test.go
=> Adding return content when create account from keycloak

horusec-manager/src/helpers/localStorage/currentUser.ts
Fixing the method to verify admin application in frontend
=> Bugfix - Verify admin application in frontend

development-kit/pkg/entities/account/repository_test.go, horusec-auth/internal/handler/auth/auth.go, horusec-auth/internal/handler/auth/auth_test.go
=> Adding validation to horusec login errors

horusec-manager/src/pages/Internal/Company/Add/index.tsx
Hidden application admin email when option is disabled.
=> Hidden application admin email when option is disabled.

horusec-cli/cmd/horusec/start/start.go
Adding validation for user response when ask if run in current directory
=> Adding validation for user response when ask if run in current directory

Makefile, deployments/docker-compose.dev.yaml, horusec-account/deployments/Dockerfile.dev, horusec-account/deployments/air/config.toml, horusec-account/internal/handlers/health/health.go, horusec-analytic/deployments/Dockerfile.dev, horusec-analytic/deployments/air/config.toml, horusec-api/deployments/Dockerfile.dev, horusec-api/deployments/air/config.toml, horusec-auth/deployments/Dockerfile.dev, horusec-auth/deployments/air/config.toml, horusec-messages/deployments/Dockerfile.dev, horusec-messages/deployments/air/config.toml
=> Compose live reload

e2e/deployments/docker-compose.application-admin.horusec.yaml, e2e/deployments/docker-compose.server.horusec.yaml, e2e/deployments/docker-compose.server.keycloak.yaml, e2e/deployments/docker-compose.server.messages.yaml
=> Change to run e2e with dockerfile of test

horusec-auth/config/cors/cors.go
=> Fixing auth cors

horusec-manager/src/pages/Internal/Home/Repositories/Add/index.tsx
=> Repository form authz groups

deployments/scripts/migration-run.sh
=> Adding stable version to migrate (#167)

deployments/scripts/migration-run.sh, horusec-auth/internal/controller/account/account.go
=> Updating develop with master

horusec-manager/src/pages/Internal/Home/Dashboard/AllVulnerabilities/index.tsx, horusec-manager/src/pages/Internal/Home/Dashboard/AllVulnerabilities/styled.ts, horusec-manager/src/pages/Internal/Home/Dashboard/VulnerabilitiesByLanguage/index.tsx, horusec-manager/src/pages/Internal/Home/Dashboard/VulnerabilitiesByLanguage/styled.ts
- Fixing error when load the donut chart with empty data.
=> Frontend - Donut charts error

horusec-manager/deployments/scripts/run-nginx.sh, horusec-manager/public/index.html, horusec-manager/src/config/keycloak.ts
=> Fixing keycloak environment variable set

horusec-manager/package-lock.json, horusec-manager/package.json, horusec-manager/src/config/endpoints.ts, horusec-manager/src/pages/Internal/Vulnerabilities/Details/index.tsx, horusec-manager/src/pages/Internal/Vulnerabilities/Details/styled.ts
- Alter localhost to use 127.0.0.1 in endpoints config.
- Linkify the url in vulnerabilities details.
=> Frontend - Linkify vulnerabilities details

HOWTO.md
=> Updating how to

horusec-cli/README.md
=> Updating horusec config json in cli readme (#242)

.github/workflows/deploy-service.yml
=> Revert "Update deploy-service.yml"

horusec-manager/src/components/Logout/index.tsx, horusec-manager/src/components/Pagination/index.tsx, horusec-manager/src/components/Splash/styled.ts, horusec-manager/src/contexts/Auth/index.tsx, horusec-manager/src/contexts/Auth/keycloak.ts, horusec-manager/src/helpers/localStorage/tokens.ts, horusec-manager/src/layouts/External/styled.ts, horusec-manager/src/pages/Internal/Dashboard/VulnerabilitiesDetails/index.tsx, horusec-manager/src/pages/Internal/Vulnerabilities/index.tsx
- Fixing logout when no have a "authType".
- Adjusting responsive of login page when screen size small.
- Fixing function to set tokens of keycloak login flow.
- Fixing count of total pages of the pagination in tables.
=> [Frontend] Fixing bugs found in production

horusec-manager/src/pages/Internal/Repositories/index.tsx, horusec-manager/src/pages/Internal/Workspaces/index.tsx
Hidden Invite users of workspaces and repositories when the "authType" is Ldap.
=> [Frontend] Hidden invite user - Ldap

development-kit/pkg/databases/relational/repository/analysis/analysis.go, horusec-analytic/internal/handlers/dashboard/dashboard.go, horusec-analytic/internal/handlers/dashboard/dashboard_test.go, horusec-manager/src/components/Pagination/index.tsx, horusec-manager/src/helpers/formatters/date.ts, horusec-manager/src/pages/Internal/Dashboard/Filters/index.tsx, horusec-manager/src/services/analytic.ts
Dashboard load data from the beginning
=> Dashboard load data from the beginning

horusec-manager/src/config/themes/dark.ts
Added elixir and shell colors in languages of dashboard
=> Added elixir and shell colors in languages of dashboard

e2e/application_admin/horusec/requests.go, e2e/server/horusec/requests.go, e2e/server/keycloak/requests.go, e2e/server/messages/requests.go, e2e/server/shared_requests.go, horusec-account/internal/router/routes/routes.go, horusec-analytic/internal/router/routes/routes.go, horusec-auth/internal/router/routes/routes.go, horusec-manager/src/services/account.ts, horusec-manager/src/services/analytic.ts, horusec-manager/src/services/company.ts, horusec-manager/src/services/repository.ts, horusec-manager/src/services/webhook.ts, horusec-messages/internal/router/routes/routes.go, horusec-webhook/internal/router/routes/routes.go
* Updating account routers
* Updating analytic routers
* Updating auth routers
* Updating messages routers
* Updating webhook routers
* Updating front end account service
* Updating front end analytic service
* Updating front end company service
* Updating front end repository service
* Updating front end webhook service
* Fixing front-end lint
* Fixing endpoint error
* Fixing tests
* Fixing tests
* Fixing tests
* Fixing e2e tests
* Fixing tokens url
* Fixing e2e tests
Co-authored-by: nathanmartinszup <nathan.martins@zup.com.br>
=> Hotfix/backend urls (#293)

horusec-api/internal/controllers/analysis/analysis.go
=> Adding repository authz groups from company

development-kit/pkg/databases/relational/repository/company/company.go, development-kit/pkg/databases/relational/repository/repository/repository.go, horusec-account/.semver.yaml
=> Fixing error in lists

horusec-auth/internal/handler/health/health.go, horusec-auth/internal/handler/health/health_test.go, horusec-auth/internal/services/ldap/ldap.go, horusec-auth/internal/services/ldap/ldap_test.go
=> Closing ldap connection after using it

horusec-manager/src/pages/Internal/Repositories/Handle/index.tsx, horusec-manager/src/pages/Internal/Workspaces/Handle/index.tsx
Added trim and adjusting functions to handle values of groups list
=> [Front-end] - Ldap group unecessary spaces and improvees

horusec-manager/.semver.yaml, horusec-manager/src/contexts/Auth/index.tsx
=> Fixing logout redirect

horusec-manager/src/pages/Internal/Repositories/Invite/index.tsx, horusec-manager/src/pages/Internal/Repositories/Invite/styled.ts, horusec-manager/src/pages/Internal/Workspaces/styled.ts
=> Adjust layout workpaces

horusec-manager/src/pages/Internal/Vulnerabilities/index.tsx, horusec-manager/src/services/repository.ts
=> change defaulthttp to http, add type error in catch

horusec-manager/src/pages/Internal/Workspaces/Users/index.tsx
=> Change type actions property

horusec-manager/src/config/themes/dark.ts, horusec-manager/src/helpers/formatters/chartData.ts, horusec-manager/src/pages/Internal/Vulnerabilities/index.tsx
- Severity levels presentation in manager
=> Severity levels presentation in manager

Makefile, deployments/scripts/update-swagger.sh, horusec-account/docs/docs.go, horusec-account/docs/swagger.json, horusec-account/docs/swagger.yaml, horusec-analytic/docs/docs.go, horusec-analytic/docs/swagger.json, horusec-analytic/docs/swagger.yaml, horusec-api/internal/handlers/management/management.go, horusec-api/internal/handlers/tokens/company/company.go, horusec-api/internal/handlers/tokens/repository/repository.go, horusec-auth/docs/docs.go, horusec-auth/docs/swagger.json, horusec-auth/docs/swagger.yaml, horusec-messages/docs/docs.go, horusec-messages/docs/swagger.json, horusec-messages/docs/swagger.yaml, horusec-webhook/docs/docs.go, horusec-webhook/docs/swagger.json, horusec-webhook/docs/swagger.yaml
* Updating docs
* Fix bug when get tokens return 500 if not found records
* Fix bug when get vulnerabilities return 500 if not found records
=> Bugfix/updating docs and fix get token 

horusec-manager/src/components/Select/index.tsx, horusec-manager/src/pages/Internal/Vulnerabilities/index.tsx
=> [Manager] remove logic that causes multiple requests

horusec-auth/internal/usecases/auth/auth.go, horusec-auth/internal/usecases/auth/auth_test.go
=> Fixing pq error

horusec-manager/src/config/i18n/enUS.json, horusec-manager/src/config/i18n/ptBR.json, horusec-manager/src/pages/Internal/Dashboard/Filters/index.tsx, horusec-manager/src/pages/Internal/Repositories/index.tsx, horusec-manager/src/pages/Internal/Settings/ChangePassword/index.tsx, horusec-manager/src/pages/Internal/Settings/index.tsx, horusec-manager/src/pages/Internal/Workspaces/index.tsx
=> [BUGFIX] [MANAGER]  - fix requests repositories and workspaces

horusec-manager/src/pages/Internal/Dashboard/AllVulnerabilities/index.tsx, horusec-manager/src/pages/Internal/Dashboard/TotalDevelopers/index.tsx, horusec-manager/src/pages/Internal/Dashboard/VulnerabilitiesByDeveloper/index.tsx, horusec-manager/src/pages/Internal/Dashboard/VulnerabilitiesByLanguage/index.tsx, horusec-manager/src/pages/Internal/Dashboard/VulnerabilitiesByRepository/index.tsx, horusec-manager/src/pages/Internal/Dashboard/VulnerabilitiesDetails/index.tsx, horusec-manager/src/pages/Internal/Dashboard/VulnerabilitiesTimeLine/index.tsx, horusec-manager/src/pages/Internal/Repositories/Invite/index.tsx, horusec-manager/src/pages/Internal/Repositories/Tokens/index.tsx, horusec-manager/src/pages/Internal/Vulnerabilities/index.tsx, horusec-manager/src/pages/Internal/Workspaces/Tokens/index.tsx
change default variable isLoading to false, because when it is as true it locks the loading. 
To
=> [HOTFIX] Set default variable isloading to false

.github/CODEOWNERS, horusec-cli/internal/services/formatters/shell/shellcheck/config.go
=> Fix shell check command

CODE_OF_CONDUCT.md
=> Fixing code of conduct email

CODE_OF_CONDUCT.md
=> Fixing code of conduct email (#417)

horusec-manager/src/config/endpoints.ts, horusec-manager/src/config/i18n/ptBR.json, horusec-manager/src/pages/External/Auth/Horusec/Login/index.tsx
Added warning in manager when the variables of services not be definned
=> Manager services variables warning

README.md
=> Adding new repository disclaimer

.github/workflows/security-pipeline.yml
=> Adding env for security pipeline job

horusec-cli/internal/services/sonarqube/sonarqube.go, horusec-cli/internal/services/sonarqube/sonarqube_test.go
=> Fix sonarqube export format

horusec-config.json, internal/services/formatters/csharp/scs/formatter.go, internal/services/formatters/elixir/sobelow/formatter.go, internal/services/git/git.go, internal/utils/vuln_hash/vuln_hash.go
=> Fix commit authors

README.md
=> Updating readme with cli requirements and zup open source forum

cmd/app/start/start.go, cmd/app/start/start_test.go, internal/controllers/analyzer/analyzer.go, internal/controllers/analyzer/analyzer_mock.go, internal/controllers/analyzer/analyzer_test.go, internal/services/formatters/go/gosec/formatter_test.go, internal/services/formatters/leaks/gitleaks/formatter_test.go
=> rename analyser to analyzer

Makefile, cmd/app/start/start.go, cmd/app/version/version.go, config/config.go, config/dist/dist.go, config/dist/dist_test.go
=> Stand alone horusec CLI

e2e/scan_languages/scan_languages_test.go, examples/swift/example1/example/example/Source/Container/HTMLViewController.swift, examples/swift/example1/example/example/Source/Container/HintVC.swift, examples/swift/example1/example/example/Source/Exercises/Injection Flaws/XSS/CrossSiteScriptingExerciseVC.swift, examples/swift/example1/example/example/Source/Exercises/Key Management/Hard Coded Keys/BrokenCryptographyExerciseVC.swift, go.mod, go.sum, internal/controllers/analyzer/analyzer.go, internal/services/engines/rules_test.go, internal/services/engines/swift/and/and.go, internal/services/engines/swift/or/or.go, internal/services/engines/swift/regular/regular.go, internal/services/engines/swift/rules.go, internal/services/formatters/default_engine_formatter_test.go, internal/services/formatters/swift/horusecswift/formatter.go
Introduce support to Swift with rules using the Horusec engine.
=> add support to Swift

internal/services/engines/swift/and/and.go, internal/services/engines/swift/or/or.go, internal/services/engines/swift/regular/regular.go
=> improvement on Swift rules description

README.md
Story details: https://app.clubhouse.io/horusec/story/123307
=> teste github

internal/helpers/messages/info.go, internal/helpers/messages/warn.go
Hey, it does not change any behavior.
I'm studying the source code and then find those variables that are unused.
Does it make sense to remove it?
=> Remove unused constant

e2e/scan_languages/scan_languages_test.go
The PR #506 was merged before the refactor of e2e tests in #505.
So this commit update the expected vulnerabities to match the new
rules added on #506.
=> tests: fix expected vulnerabities on Javascript

internal/services/formatters/csharp/scs/severities/dotnet_critical.go
=> csharp: fix false positive hardcoded password

.github/workflows/build.yaml, .github/workflows/coverage.yml, .github/workflows/deploy-cli-language.yml, .github/workflows/e2e.yml, .github/workflows/license.yaml, .github/workflows/release.yml, .github/workflows/test.yml
=> ci: bump Go version 1.17 on workflows

goreleaser.yml
=> ci: generate .deb and .rpm files

renovate.json
scheduling renovate to run only on weekends
=> renovate: scheduling to run every weekend

ROADMAP.md
Published reviewed English version of ROADMAP.MD
=> Translating ROADMAP.md to English

.github/workflows/dco.yaml
=> ci: create workflow to validate commits signatures for DCO

e2e/scan_languages/scan_languages_test.go
=> tests: fix e2e tests of Ruby

.github/workflows/dco.yaml
Change dco to run on pull requests as specified on docs so we have less chance of getting an error
=> dco: updating to run as specified on docs

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md
Signed-off-by: jessica.olinda@zup.com.br <jessica.olinda@zup.com.br>
**- What I did** Updated README.md and CONTRIBUTING.md. 
**- Description for the changelog** Updated README and CONTRIBUTING
=> Updated README and CONTRIBUTING

.github/CODEOWNERS
Adding * to add reviewers on every change
Signed-off-by: nathanmartinszup <nathan.martins@zup.com.br>
=> github:code owners

Makefile
=> scripts: fix branch name of coverage script on devkit

e2e/scan_languages/scan_languages_test.go
=> tests: fix Python Safety e2e

internal/services/engines/rules_test.go, internal/services/engines/samples_test.go
This commit refactor the tests of leaks rules to be more generic and be
more easily to add new test cases. The leak tests was removed on PR #624.
So this commit re-introduce the tests but with some improvements
=> tests: refactor leaks tests to be more generic

internal/services/engines/csharp/rules.go, internal/services/engines/dart/rules.go, internal/services/engines/java/rules.go, internal/services/engines/jvm/rules.go, internal/services/engines/kubernetes/rules.go, internal/services/engines/leaks/rules.go, internal/services/engines/nginx/rules.go, internal/services/engines/nodejs/rules.go, internal/services/engines/rules_test.go, internal/services/engines/swift/rules.go
=> rules: change rule ids to <HS-LANGUAGE-ID> template

e2e/scan_languages/scan_languages_test.go
Signed-off-by: nathanmartinszup <nathan.martins@zup.com.br>
=> Updated total vulnerabiltiies in javascript npm e2e

.github/workflows/alpha.yml
Signed-off-by: nathanmartinszup <nathan.martins@zup.com.br>
=> alpha workflow: added step to delete alpha to avoid outdate release

.github/workflows/alpha.yml, .github/workflows/build.yaml, .github/workflows/coverage.yml, .github/workflows/deploy-cli-language.yml, .github/workflows/e2e.yml, .github/workflows/license.yaml, .github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/security.yml, .github/workflows/test.yml, horusec-config.json
Updating permissions to match [scorecard](https://github.com/ossf/scorecard) standards, but token permissions is still in [WIP](https://github.com/ossf/scorecard/issues/942) and it's a problemactic subject on scorecard yet. I will checkout updates to keep us informed about it.
=> actions: update permissions and add show-vulnerabilities to security

renovate.json
=> renovate: add signoff body to make commits DCO compliant

renovate.json
=> renovate: fix renovate bot name on commit body

internal/entities/custom_rules/custom_rule.go, internal/entities/custom_rules/custom_rule_test.go, internal/services/custom_rules/custom_rules_example.json, internal/services/custom_rules/service.go, internal/services/engines/csharp/rule_manager.go, internal/services/engines/dart/rule_manager.go, internal/services/engines/java/rule_manager.go, internal/services/engines/kotlin/rules.go, internal/services/engines/kubernetes/rule_manager.go, internal/services/engines/leaks/rule_manager.go, internal/services/engines/nginx/rule_manager.go, internal/services/engines/nodejs/rule_manager.go
Introduce a validation to check for duplicate IDs when using custom
rules. This validation will check if a custom rule id already exists on
standard rules of Horusec.
=> rules: validate duplicates when using custom rules

internal/services/formatters/interface.go, internal/services/formatters/service.go, internal/services/formatters/service_mock.go, internal/services/formatters/service_test.go
=> formatter: remove unused methods from interface

internal/usecases/cli/cli.go
=> flags: fix validation of show-vulnerabilities-types flag

cmd/app/start/start.go
=> cmd/start: fix typo on Analyzer doc

internal/services/engines/nodejs/samples_test.go, internal/services/formatters/csharp/dotnet_cli/formatter.go, internal/services/formatters/generic/trivy/entities/vulnerability.go, internal/services/formatters/javascript/npmaudit/formatter.go, internal/utils/file/file.go
=> lint: fix some lint errors from golangci v1.43.0 version

cmd/app/start/start_test.go, internal/controllers/language_detect/language_detect_test.go, internal/helpers/messages/error.go, internal/usecases/cli/cli.go, internal/usecases/cli/cli_test.go
=>  Fix some tests validation and usecases

go.mod, go.sum, internal/controllers/language_detect/language_detect_test.go, internal/helpers/messages/error.go, internal/services/formatters/csharp/scs/formatter.go, internal/utils/file/file.go, internal/utils/file/file_test.go, internal/utils/testutil/examples.go
=> utils_file: improving tests and functions

.github/workflows/e2e.yml, e2e/analysis/analysis_test.go, e2e/commands/start/start_test.go, internal/utils/testutil/binary.go
Some places were not using previously defined "enums".
=> e2e:chore - some places were not using previously defined "enums".

e2e/commands/generate/generate_test.go, e2e/commands/start/start_test.go, go.mod, go.sum, internal/controllers/analyzer/analyzer.go, internal/utils/testutil/examples.go, internal/utils/testutil/path.go
Tests for start with global flags
=> e2e:chore - tests for start with global flags

e2e/commands/start/start_test.go, internal/controllers/printresults/print_results_test.go
Add tests for the output format and json outuput file flags
=> e2e:chore - tests for the output format and json outuput file flags

e2e/commands/start/start_test.go
- New refactoring 
- Create tests for certificate path flag
- Create new file helper in testutils
=> e2e:feat - certificate path

e2e/commands/start/start_test.go
e2e: test for `--return-error` flag
=> e2e:chore - return error flag

internal/utils/json/json.go, internal/utils/json/json_test.go, internal/utils/valueordefault/value_or_default.go, internal/utils/valueordefault/value_or_default_test.go
Remove unused functions form utils/valueordefault and utils/json
packages.
=> utils:chore - remove unused functions 

e2e/commands/start/start_test.go
Tests e2e for disable docker and repository name flags.
=> e2e:chore - test for disable docker and repository name

e2e/commands/start/start_test.go
Test e2e for `--ignore-severity` flag
=> e2e:chore - test for ignore severity flag

e2e/commands/start/start_test.go
E2e  test for `--insecure-skip-verify` flag
Run `test-e2e`
N/A
=> e2e:chore - test for insecure skip verify flag

e2e/commands/start/start_test.go, internal/utils/copy/copy_test.go
Test for `--horusec-url` and `--headers` flags
run `make test-e2e`
N/A
=> e2e:chore - test for horusec url api and headers flags

e2e/commands/start/start_test.go
E2e test for the `--ignore` flag.
run `test-e2e`
N/A
=> e2e:chore - test for the ignore flag

e2e/commands/start/start_test.go
E2e test for the `--enable-shellcheck` flag.
run `make test-e2e`
N/A
=> e2e:chore - test for enable shell check flag

e2e/commands/start/start_test.go
test for `container-bind-project-path` flag
run `make test-e2e`
N/A
=> e2e:chore - test for container bind project path flag.

e2e/commands/start/start_test.go, internal/services/docker/client/docker_config_test.go, internal/utils/prompt/prompt_test.go
E2e tests for the `--show-vulnerabilities-type` and `--project-path` flags
Run `make test-e2e`
N/A
=> e2e:chore - test for the show vulnerabilities and project path flags

Makefile
This pull request changes the way that we install some tools that we use in our makefile, the ideia is avoid outdated dependencies and use the auto updates by renovate bot. Also added a format command with two news auto formaters [gofumpt](https://github.com/mvdan/gofumpt) and [gci](https://github.com/daixiang0/gci).
This pull request depends on the #809, which contains all the changes made by the formaters. 
=> makefile:chore - updating makefile to avoid outdate dependencies

internal/services/engines/javascript/rules.go, internal/services/engines/javascript/rules_test.go, internal/services/engines/javascript/samples_test.go
Unit test for `HS-JAVASCRIPT-19` rule.
Issue: #630
=> engine:chore - add test for HS-JAVASCRIPT-19 rule.

.golangci.yml
Adding [gofumpt](https://github.com/mvdan/gofumpt), [gci](https://github.com/daixiang0/gci) linters and fixing import prefixes path. Some commented linters were also added, the idea is that they are uncommented one by one and the related errors are corrected, for each one will be separate pull requests opened with the corrections.
Depends on #809 which contains all the imports and gofumpt  fixes.
=> lint:chore - updating lint config file

internal/services/custom_rules/service.go, internal/services/custom_rules/service_test.go
=> customrules:chore - improve tests asserts and code cleaning

CONTRIBUTING.md, README.md
Signed-off-by: jessica-tw <jessica.olinda@zup.com.br>
**- What I did** - Some fixes to Readme and Contributing Guide. 
**- Description for the changelog** Some fixes to Readme and Contributing Guide.
=> readme:fix - Minor fixes to Contributing and Readme

cmd/app/version/version.go, config/dist/dist.go, config/dist/dist_test.go
=> config/dist:chore -  add docs about stand-alone builds

renovate.json
=> renovate:chore - updating renovate json to follow commit message pattern

.github/workflows/alpha.yml, .github/workflows/release-beta.yml, .github/workflows/release-new.yml, .github/workflows/release-rc.yml
Remove unused import GPG step on release workflows
=> release:bugfix - removing import GPG from release workflows

.github/workflows/alpha.yml, .github/workflows/release-beta.yml, .github/workflows/release-new.yml, .github/workflows/release-rc.yml
=> Revert "release:bugfix - removing import GPG from release workflows"

internal/controllers/language_detect/language_detect.go, internal/helpers/messages/warn.go
=> language_detect:chore - improve code readability

e2e/commands/start/start_test.go, internal/utils/testutil/file.go
Signed-off-by: oliveira.felipe <oliveira.felipe@zup.com.br>
- Create test for custom rules path flag
- 
=> e2e:chore - Create test for custom rules path flag

e2e/commands/start/start_test.go, internal/enums/errors/errors.go, internal/services/formatters/service.go, mage.go, magefile.go
=> logs:chore - improve logs when analysis gets errors

BUILD.md
Signed-off-by: Henrique Rodrigues <henrique.rodrigues@zup.com.br>
Review the content and add the BUILD.md file for this project
In the project's root, check the BUILD.md file.
BUILD.md file with environment and build specifications of the project.
=> docs:add the BUILD.md file for horusec-cli

goreleaser.yml
=> goreleaser:bugfix - adding missing dot to name template Major.Minor

README.md
Adicionar a opção "-k" no curl para evitar o problema abaixo:
curl: (60) SSL certificate problem: self signed certificate in certificate chain
More details here: https://curl.haxx.se/docs/sslcerts.html
=> Update README.md - adding -k option

cmd/app/start/start.go, cmd/app/start/start_test.go, internal/controllers/requirements/docker/docker.go, internal/controllers/requirements/git/git.go, internal/controllers/requirements/requirements.go, internal/controllers/requirements/requirements_test.go, internal/utils/testutil/requirements_mock.go
=> requirements:bugfix - now returns error instead of panicking when fail

internal/enums/images/images.go
Update to complete patch started in #880.
=> images:fix - upgrade Ruby Docker image

internal/services/formatters/elixir/sobelow/formatter.go, internal/services/formatters/elixir/sobelow/formatter_test.go, internal/services/formatters/elixir/sobelow/output.go
This commit add some new asserts on successful parsing Sobelow
results, to verify that all fields of Vulnerability was filled.
removed and the Sobelow schema output was moved to sobelow package.
Updates #718
=> sobelow:chore - improve tests and code cleaning

.github/workflows/security.yml, Makefile
=> workflow/security:chore - updating security workflow to use latest rc

deployments/scripts/install.sh
In cases that users are using the latest-beta/rc, they should get the
latest instead of the beta/rc if the latest is in a greater version.
=> install/sh:bugfix - updating install sh to install latest if more recent 

internal/services/engines/java/rules.go
Signed-off-by: Maximillian Arruda <dearrudam@gmail.com>
Added CVE-2021-44832 detail to the description of the HS-JAVA-150 rule
=> Added CVE-2021-44832 detail to the description of the HS-JAVA-150 rule

internal/services/engines/kubernetes/rules.go, internal/services/engines/kubernetes/rules_test.go, internal/services/engines/kubernetes/samples_test.go
Add improvements for swift rules with scenarios vulnerables and safe codes in yours tests.
Follow the issue #630 for more details.
=> kubernetes:chore - Improvements Tests of all Kubernetes Rules

deployments/Dockerfile, deployments/Dockerfile-gorelease-amd64, deployments/Dockerfile-gorelease-arm64
Previously we was not updating the installed packages of alpine, which
could cause vulnerability issues, as the image used may contain outdated
packages.
=> dockerfile:fix - update and upgrade packages

deployments/Dockerfile, deployments/Dockerfile-gorelease-amd64, deployments/Dockerfile-gorelease-arm64
=> dockerfiles:bugfix - adding no cache flag

deployments/Dockerfile-gorelease-amd64, deployments/Dockerfile-gorelease-arm64
Docker in docker 20.10-git contains some outdated dependencies with
vulnerabilities, this pull request contains a new build image
with fixes for this issues.
=> dockerfile:bugfix - updating dockerfiles docker base image

.github/workflows/build.yaml
In this commit was added a new workflow to check if the when dispatch
alpha, beta, rc, release final any problem was detected in
developement time.
=> chore:workflow - Added new workflow to validate release workflows

CONTRIBUTING.md
Signed-off-by: Henrique Rodrigues <henrique.rodrigues@zup.com.br>
I added the issues section
Access the CONTRIBUTING.md file of this branch, check section 2.3
Adding an issue section as a prerequisite before contributing with a PR
=> docs: add issues section

.github/workflows/build.yaml
=> release:build - Removing GPG and sign images from build.yaml

internal/services/docker/docker_api.go
=> docker:fix - missing image name on debug log

internal/services/engines/java/rule_manager.go, internal/services/engines/java/rules.go, internal/services/engines/java/rules_test.go, internal/services/engines/java/sample_test.go, internal/services/engines/rules_test.go
This Commit refer the issue #995 
=> java:feature - Add Rule for CVE-2022-21724

internal/services/engines/dart/rules.go, internal/services/engines/dart/rules_test.go, internal/services/engines/dart/sample.go
In this commit I changed to add Safe and Unsafe code
in all rules of the dart. Reference from issue https://github.com/ZupIT/horusec/issues/630 and https://github.com/ZupIT/horusec/issues/1020.
=> dart:chore - Adding improvements on dart rules

internal/services/engines/kubernetes/rules.go, internal/services/engines/kubernetes/samples.go
In this commit I changed to add Safe and Unsafe code
in all rules of the k8s. Reference from issue #630 and #1020.
=> k8s:chore - Adding improvements on k8s rules

internal/services/engines/swift/rules.go, internal/services/engines/swift/samples.go
In this commit I changed to add Safe and Unsafe code
in all rules of the swift.  Reference from issue #630 and #1020.
=> swift:chore - Adding improvements on swift rules

internal/services/custom_rules/custom_rule_test.go
Signed-off-by: “Adam <“adam88morris@gmail.com”>
Updated the tests in internal/services/custom_rules to be table tests to improve readability.
`go test -v ./internal/services/custom_rules -count 1000` runs the tests in this package 1000 times confirming they are not flaky or inconsistent.
Refactored custom_rules tests to use table tests
=> custom_rules:chore - Refactored tests for custom_rules to table tests

SECURITY.md
This pull request adds the SECURITY.md documentation.
Signed-off-by: Lucas Bruno Ferreira <lucas.bruno@zup.com.br>
=> docs:feat - Security Policies

internal/services/engines/javascript/rule_manager.go, internal/services/engines/javascript/rules.go, internal/services/engines/javascript/rules_test.go, internal/services/engines/javascript/samples.go, internal/services/engines/rules_test.go
This commit implements vulnerable and safe samples for the javascript rules.
Signed-off-by: Lucas Bruno Ferreira <lucas.bruno@zup.com.br>
=> javascript:chore - Vulnerable and Safe samples of javascript.

internal/controllers/analyzer/analyzer.go
=> analyzer:fix - Fixing details wrong

ROADMAP.md
=> roadmap:feat - Public Roadmap

internal/services/engines/java/rules.go
**- Added CAPEC and CWE to Clipboard findings**
Both CAPEC and CWE were added to Clipboard findings
=> Added CAPEC and CWE to Clipboard findings

.github/CODEOWNERS, .github/workflows/coverage.yml, .github/workflows/test.yml, e2e/analysis/test_case.go, internal/controllers/language_detect/language_detect.go, internal/controllers/language_detect/language_detect_test.go, internal/services/formatters/generic/deployments/Dockerfile
=> e2e:hotfix - Fixing problems on e2e and github files
